
before_script: 
- chmod 0555 ./node_modules/.bin/jest 
- chmod +x coveralls

language: node_js
node_js:
- node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm cache clean --force
- npm update
install:
- npm install
script:
- npm run test
- npm run coveralls